global:
  scrape_interval: 5s

scrape_configs:
  - job_name: searchapi
    static_configs:
      - targets:
          - searchapi:9102

  - job_name: indexer
    static_configs:
      - targets:
          - indexer:9101
